// @generated by mbus-codegen via build.rs. Do not edit manually.
// Rust owns all register/coil state. C receives write-notification callbacks.
// Uses the hand-written server FFI infrastructure (pool, transport, config).

use core::ffi::c_void;
use core::ptr;
use crate::c::server::callbacks::*;
use mbus_server::{CoilMap, CoilsModel, DiscreteInputMap, DiscreteInputsModel, HoldingRegisterMap, HoldingRegistersModel, modbus_app};

/// Status returned by write-notification hooks and FFI accessors.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MbusHookStatus {
    MbusHookOk = 0,
    MbusHookIllegalDataAddress = 1,
    MbusHookIllegalDataValue = 2,
    MbusHookDeviceFailure = 3,
}

unsafe extern "C" {
    fn app_on_write_blink_delay(ctx: *mut c_void, address: u16, value: u16) -> MbusHookStatus;
    fn app_on_write_led_green(ctx: *mut c_void, address: u16, value: u8) -> MbusHookStatus;
    fn app_on_write_led_red(ctx: *mut c_void, address: u16, value: u8) -> MbusHookStatus;
    fn app_on_write_led_yellow(ctx: *mut c_void, address: u16, value: u8) -> MbusHookStatus;
    /// Acquire your RTOS mutex / critical section before Rust state is mutated.
    /// Single-threaded bare-metal: implement as an empty function.
    fn mbus_app_lock();
    /// Release the lock acquired by mbus_app_lock().
    fn mbus_app_unlock();
}

#[derive(Debug, Default, CoilsModel)]
pub struct AppCoils {
    #[coil(addr = 0)]
    pub led_yellow: bool,
    #[coil(addr = 1)]
    pub led_red: bool,
    #[coil(addr = 2)]
    pub led_green: bool,
}

#[derive(Debug, Default, DiscreteInputsModel)]
pub struct AppDiscreteInputs {
    #[discrete_input(addr = 0)]
    pub button_user: bool,
}

#[derive(Debug, Default, HoldingRegistersModel)]
pub struct AppHolding {
    #[reg(addr = 0)]
    pub blink_delay: u16,
}

/// Generated server app for: STM32 Modbus Server
#[derive(Debug, Default)]
#[modbus_app(coils(coils), discrete_inputs(discrete_inputs), holding_registers(holding))]
pub struct AppModel {
    pub coils: AppCoils,
    pub discrete_inputs: AppDiscreteInputs,
    pub holding: AppHolding,
}

static mut APP_MODEL: Option<AppModel> = None;

#[inline(always)]
fn dispatch_write_coil(ctx: *mut c_void, address: u16, value: u8) -> MbusHookStatus {
    match address {
        0 => unsafe { app_on_write_led_yellow(ctx, address, value) },
        1 => unsafe { app_on_write_led_red(ctx, address, value) },
        2 => unsafe { app_on_write_led_green(ctx, address, value) },
        _ => MbusHookStatus::MbusHookIllegalDataAddress,
    }
}

#[inline(always)]
fn dispatch_write_holding(ctx: *mut c_void, address: u16, value: u16) -> MbusHookStatus {
    match address {
        0 => unsafe { app_on_write_blink_delay(ctx, address, value) },
        _ => MbusHookStatus::MbusHookIllegalDataAddress,
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_get_coil(
    _ctx: *mut c_void,
    address: u16,
    out_value: *mut u8,
) -> MbusHookStatus {
    if out_value.is_null() { return MbusHookStatus::MbusHookDeviceFailure; }
    unsafe {
        mbus_app_lock();
        let val = (&*ptr::addr_of!(APP_MODEL)).as_ref().and_then(|app| match address {
            0 => Some(app.coils.led_yellow as u8),
            _ => None,
        });
        mbus_app_unlock();
        match val {
            Some(v) => { *out_value = v; MbusHookStatus::MbusHookOk }
            None => MbusHookStatus::MbusHookIllegalDataAddress,
        }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_set_coil(
    ctx: *mut c_void,
    address: u16,
    value: u8,
) -> MbusHookStatus {
    let st = dispatch_write_coil(ctx, address, value);
    if st != MbusHookStatus::MbusHookOk { return st; }
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() {
            match address {
                0 => app.coils.led_yellow = value != 0,
                1 => app.coils.led_red = value != 0,
                2 => app.coils.led_green = value != 0,
                _ => {}
            }
        }
        mbus_app_unlock();
    }
    MbusHookStatus::MbusHookOk
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_get_discrete_input(
    _ctx: *mut c_void,
    address: u16,
    out_value: *mut u8,
) -> MbusHookStatus {
    if out_value.is_null() { return MbusHookStatus::MbusHookDeviceFailure; }
    unsafe {
        mbus_app_lock();
        let val = (&*ptr::addr_of!(APP_MODEL)).as_ref().and_then(|app| match address {
            0 => Some(app.discrete_inputs.button_user as u8),
            _ => None,
        });
        mbus_app_unlock();
        match val {
            Some(v) => { *out_value = v; MbusHookStatus::MbusHookOk }
            None => MbusHookStatus::MbusHookIllegalDataAddress,
        }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_get_holding_register(
    _ctx: *mut c_void,
    address: u16,
    out_value: *mut u16,
) -> MbusHookStatus {
    if out_value.is_null() { return MbusHookStatus::MbusHookDeviceFailure; }
    unsafe {
        mbus_app_lock();
        let val = (&*ptr::addr_of!(APP_MODEL)).as_ref().and_then(|app| match address {
            0 => Some(app.holding.blink_delay()),
            _ => None,
        });
        mbus_app_unlock();
        match val {
            Some(v) => { *out_value = v; MbusHookStatus::MbusHookOk }
            None => MbusHookStatus::MbusHookIllegalDataAddress,
        }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_set_holding_register(
    ctx: *mut c_void,
    address: u16,
    value: u16,
) -> MbusHookStatus {
    let st = dispatch_write_holding(ctx, address, value);
    if st != MbusHookStatus::MbusHookOk { return st; }
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() {
            match address {
                0 => app.holding.set_blink_delay(value),
                _ => {}
            }
        }
        mbus_app_unlock();
    }
    MbusHookStatus::MbusHookOk
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_get_input_register(
    _ctx: *mut c_void,
    address: u16,
    out_value: *mut u16,
) -> MbusHookStatus {
    let _ = (address, out_value);
    MbusHookStatus::MbusHookIllegalDataAddress
}

#[inline(always)]
fn hook_to_exception(st: MbusHookStatus) -> MbusServerExceptionCode {
    match st {
        MbusHookStatus::MbusHookOk => MbusServerExceptionCode::Ok,
        MbusHookStatus::MbusHookIllegalDataAddress => MbusServerExceptionCode::IllegalDataAddress,
        MbusHookStatus::MbusHookIllegalDataValue => MbusServerExceptionCode::IllegalDataValue,
        _ => MbusServerExceptionCode::ServerDeviceFailure,
    }
}

// ---------------------------------------------------------------------------
// Handler callbacks matching MbusServerHandlers signatures.
// Wire these into a MbusServerHandlers struct or use mbus_server_default_handlers().
// ---------------------------------------------------------------------------

/// Handler for FC 0x01 — Read Coils.  Reads from model state.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mbus_gen_on_read_coils(
    req: *mut MbusServerReadCoilsReq,
    _userdata: *mut c_void,
) -> MbusServerExceptionCode {
    if req.is_null() { return MbusServerExceptionCode::ServerDeviceFailure; }
    let req = unsafe { &mut *req };
    unsafe {
        mbus_app_lock();
        let result = (&*ptr::addr_of!(APP_MODEL))
            .as_ref()
            .and_then(|app| {
                let out = core::slice::from_raw_parts_mut(req.out_data, req.out_data_len);
                app.coils.encode(req.address, req.quantity, out).ok()
            });
        mbus_app_unlock();
        match result {
            Some(n) => { req.out_byte_count = n; MbusServerExceptionCode::Ok }
            None => MbusServerExceptionCode::IllegalDataAddress,
        }
    }
}

/// Handler for FC 0x05 — Write Single Coil.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mbus_gen_on_write_single_coil(
    req: *const MbusServerWriteSingleCoilReq,
    userdata: *mut c_void,
) -> MbusServerExceptionCode {
    if req.is_null() { return MbusServerExceptionCode::ServerDeviceFailure; }
    let req = unsafe { &*req };
    let st = dispatch_write_coil(userdata, req.address, req.value as u8);
    if st != MbusHookStatus::MbusHookOk { return hook_to_exception(st); }
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() {
            let _ = app.coils.write_single(req.address, req.value);
        }
        mbus_app_unlock();
    }
    MbusServerExceptionCode::Ok
}

/// Handler for FC 0x0F — Write Multiple Coils.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mbus_gen_on_write_multiple_coils(
    req: *const MbusServerWriteMultipleCoilsReq,
    userdata: *mut c_void,
) -> MbusServerExceptionCode {
    if req.is_null() { return MbusServerExceptionCode::ServerDeviceFailure; }
    let req = unsafe { &*req };
    let values = unsafe { core::slice::from_raw_parts(req.values, req.values_len) };
    for i in 0..req.quantity {
        let byte_idx = i as usize / 8;
        let bit = if byte_idx < values.len() { (values[byte_idx] >> (i % 8)) & 1 } else { 0 };
        let st = dispatch_write_coil(userdata, req.starting_address.wrapping_add(i), bit);
        if st != MbusHookStatus::MbusHookOk { return hook_to_exception(st); }
    }
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() {
            let _ = app.coils.write_many_from_packed(
                req.starting_address, req.quantity, values, 0,
            );
        }
        mbus_app_unlock();
    }
    MbusServerExceptionCode::Ok
}

/// Handler for FC 0x02 — Read Discrete Inputs.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mbus_gen_on_read_discrete_inputs(
    req: *mut MbusServerReadDiscreteInputsReq,
    _userdata: *mut c_void,
) -> MbusServerExceptionCode {
    if req.is_null() { return MbusServerExceptionCode::ServerDeviceFailure; }
    let req = unsafe { &mut *req };
    unsafe {
        mbus_app_lock();
        let result = (&*ptr::addr_of!(APP_MODEL))
            .as_ref()
            .and_then(|app| {
                let out = core::slice::from_raw_parts_mut(req.out_data, req.out_data_len);
                app.discrete_inputs.encode(req.address, req.quantity, out).ok()
            });
        mbus_app_unlock();
        match result {
            Some(n) => { req.out_byte_count = n; MbusServerExceptionCode::Ok }
            None => MbusServerExceptionCode::IllegalDataAddress,
        }
    }
}

/// Handler for FC 0x03 — Read Holding Registers.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mbus_gen_on_read_holding_registers(
    req: *mut MbusServerReadHoldingRegistersReq,
    _userdata: *mut c_void,
) -> MbusServerExceptionCode {
    if req.is_null() { return MbusServerExceptionCode::ServerDeviceFailure; }
    let req = unsafe { &mut *req };
    unsafe {
        mbus_app_lock();
        let result = (&*ptr::addr_of!(APP_MODEL))
            .as_ref()
            .and_then(|app| {
                let out = core::slice::from_raw_parts_mut(req.out_data, req.out_data_len);
                app.holding.encode(req.address, req.quantity, out).ok()
            });
        mbus_app_unlock();
        match result {
            Some(n) => { req.out_byte_count = n; MbusServerExceptionCode::Ok }
            None => MbusServerExceptionCode::IllegalDataAddress,
        }
    }
}

/// Handler for FC 0x06 — Write Single Register.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mbus_gen_on_write_single_register(
    req: *const MbusServerWriteSingleRegisterReq,
    userdata: *mut c_void,
) -> MbusServerExceptionCode {
    if req.is_null() { return MbusServerExceptionCode::ServerDeviceFailure; }
    let req = unsafe { &*req };
    let st = dispatch_write_holding(userdata, req.address, req.value);
    if st != MbusHookStatus::MbusHookOk { return hook_to_exception(st); }
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() {
            let _ = app.holding.write_single(req.address, req.value);
        }
        mbus_app_unlock();
    }
    MbusServerExceptionCode::Ok
}

/// Handler for FC 0x10 — Write Multiple Registers.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mbus_gen_on_write_multiple_registers(
    req: *const MbusServerWriteMultipleRegistersReq,
    userdata: *mut c_void,
) -> MbusServerExceptionCode {
    if req.is_null() { return MbusServerExceptionCode::ServerDeviceFailure; }
    let req = unsafe { &*req };
    let values = unsafe { core::slice::from_raw_parts(req.values, req.values_len) };
    for (i, &v) in values.iter().enumerate() {
        let addr = req.starting_address.wrapping_add(i as u16);
        let st = dispatch_write_holding(userdata, addr, v);
        if st != MbusHookStatus::MbusHookOk { return hook_to_exception(st); }
    }
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() {
            let _ = app.holding.write_many(req.starting_address, values);
        }
        mbus_app_unlock();
    }
    MbusServerExceptionCode::Ok
}


/// Initialise the generated Modbus register/coil model.
///
/// Must be called once before creating the server with `mbus_tcp_server_new` or
/// `mbus_serial_server_new`.
#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_model_init() {
    unsafe { APP_MODEL = Some(AppModel::default()); }
}

/// Returns a fully-populated `MbusServerHandlers` struct pointing to the
/// generated handler callbacks.  Pass the returned struct to
/// `mbus_tcp_server_new` or `mbus_serial_server_new`.
///
/// `userdata` is forwarded to write-notification hooks as their first argument.
#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_default_handlers(
    userdata: *mut c_void,
) -> MbusServerHandlers {
    MbusServerHandlers {
        userdata,
        on_read_coils: Some(mbus_gen_on_read_coils),
        on_write_single_coil: Some(mbus_gen_on_write_single_coil),
        on_write_multiple_coils: Some(mbus_gen_on_write_multiple_coils),
        on_read_discrete_inputs: Some(mbus_gen_on_read_discrete_inputs),
        on_read_holding_registers: Some(mbus_gen_on_read_holding_registers),
        on_write_single_register: Some(mbus_gen_on_write_single_register),
        on_write_multiple_registers: Some(mbus_gen_on_write_multiple_registers),
        #[cfg(feature = "registers")]
        on_mask_write_register: None,
        #[cfg(feature = "registers")]
        on_read_write_multiple_registers: None,
        #[cfg(feature = "registers")]
        on_read_input_registers: None,
        #[cfg(feature = "fifo")]
        on_read_fifo_queue: None,
        #[cfg(feature = "file-record")]
        on_read_file_record: None,
        #[cfg(feature = "file-record")]
        on_write_file_record: None,
        #[cfg(feature = "diagnostics")]
        on_read_exception_status: None,
        #[cfg(feature = "diagnostics")]
        on_diagnostics: None,
        #[cfg(feature = "diagnostics")]
        on_get_comm_event_counter: None,
        #[cfg(feature = "diagnostics")]
        on_get_comm_event_log: None,
        #[cfg(feature = "diagnostics")]
        on_report_server_id: None,
        #[cfg(feature = "diagnostics")]
        on_read_device_identification: None,
    }
}

// Named field accessors — push/pull values from your application code.
// These bypass write-notification hooks (app-side push, not a Modbus write).

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_set_led_yellow(value: u8) {
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() { app.coils.led_yellow = value != 0; }
        mbus_app_unlock();
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_get_led_yellow(out_value: *mut u8) -> MbusHookStatus {
    if out_value.is_null() { return MbusHookStatus::MbusHookDeviceFailure; }
    unsafe {
        mbus_app_lock();
        let val = (&*ptr::addr_of!(APP_MODEL)).as_ref().map(|app| app.coils.led_yellow as u8);
        mbus_app_unlock();
        match val {
            Some(v) => { *out_value = v; MbusHookStatus::MbusHookOk }
            None => MbusHookStatus::MbusHookDeviceFailure,
        }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_set_led_red(value: u8) {
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() { app.coils.led_red = value != 0; }
        mbus_app_unlock();
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_get_led_red(out_value: *mut u8) -> MbusHookStatus {
    if out_value.is_null() { return MbusHookStatus::MbusHookDeviceFailure; }
    unsafe {
        mbus_app_lock();
        let val = (&*ptr::addr_of!(APP_MODEL)).as_ref().map(|app| app.coils.led_red as u8);
        mbus_app_unlock();
        match val {
            Some(v) => { *out_value = v; MbusHookStatus::MbusHookOk }
            None => MbusHookStatus::MbusHookDeviceFailure,
        }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_set_led_green(value: u8) {
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() { app.coils.led_green = value != 0; }
        mbus_app_unlock();
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_get_led_green(out_value: *mut u8) -> MbusHookStatus {
    if out_value.is_null() { return MbusHookStatus::MbusHookDeviceFailure; }
    unsafe {
        mbus_app_lock();
        let val = (&*ptr::addr_of!(APP_MODEL)).as_ref().map(|app| app.coils.led_green as u8);
        mbus_app_unlock();
        match val {
            Some(v) => { *out_value = v; MbusHookStatus::MbusHookOk }
            None => MbusHookStatus::MbusHookDeviceFailure,
        }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_set_button_user(value: u8) {
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() { app.discrete_inputs.button_user = value != 0; }
        mbus_app_unlock();
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_get_button_user(out_value: *mut u8) -> MbusHookStatus {
    if out_value.is_null() { return MbusHookStatus::MbusHookDeviceFailure; }
    unsafe {
        mbus_app_lock();
        let val = (&*ptr::addr_of!(APP_MODEL)).as_ref().map(|app| app.discrete_inputs.button_user as u8);
        mbus_app_unlock();
        match val {
            Some(v) => { *out_value = v; MbusHookStatus::MbusHookOk }
            None => MbusHookStatus::MbusHookDeviceFailure,
        }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_set_blink_delay(value: u16) {
    unsafe {
        mbus_app_lock();
        if let Some(app) = (&mut *ptr::addr_of_mut!(APP_MODEL)).as_mut() { app.holding.set_blink_delay(value); }
        mbus_app_unlock();
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn mbus_server_get_blink_delay(out_value: *mut u16) -> MbusHookStatus {
    if out_value.is_null() { return MbusHookStatus::MbusHookDeviceFailure; }
    unsafe {
        mbus_app_lock();
        let val = (&*ptr::addr_of!(APP_MODEL)).as_ref().map(|app| app.holding.blink_delay());
        mbus_app_unlock();
        match val {
            Some(v) => { *out_value = v; MbusHookStatus::MbusHookOk }
            None => MbusHookStatus::MbusHookDeviceFailure,
        }
    }
}

