#ifndef MODBUS_RS_SERVER_H
#define MODBUS_RS_SERVER_H

#pragma once

/* Auto-generated by cbindgen - DO NOT EDIT */

#include <stdint.h>
#include <stdbool.h>

/**
 * Maximum number of downstream channels per gateway instance.
 */
#define MAX_DOWNSTREAM_CHANNELS 8

/**
 * Pipeline / transaction-map size for sync gateway poll cycles (always 1).
 */
#define TXN_SIZE 1

/**
 * Maximum number of exact-unit routing entries per gateway instance.
 */
#define MAX_UNIT_ROUTES 32

/**
 * Maximum number of unit-ID-range routing entries per gateway instance.
 */
#define MAX_RANGE_ROUTES 8

/**
 * Maximum byte buffer size passed to vtable read callbacks.
 */
#define VTABLE_BUF_BYTES 256

/**
 * Maximum byte buffer size passed to vtable read callbacks.
 */
#define VTABLE_BUF_BYTES 256

/**
 * Maximum word (u16) buffer size passed to vtable read callbacks.
 */
#define VTABLE_BUF_WORDS 128

/**
 * Maximum word (u16) buffer size passed to vtable read callbacks.
 */
#define VTABLE_BUF_WORDS 128

/**
 * C-compatible status code returned by every `mbus_*` function.
 *
 * `MBUS_OK` (0) means the request was successfully queued. Actual response data
 * is delivered later via the callbacks in `MbusCallbacks`.
 */
typedef enum MbusStatusCode {
    /**
     * Success.
     */
    MbusOk = 0,
    /**
     * Frame parse error.
     */
    MbusErrParseError,
    /**
     * Basic parse error.
     */
    MbusErrBasicParseError,
    /**
     * Response timeout.
     */
    MbusErrTimeout,
    /**
     * Modbus exception response.
     */
    MbusErrModbusException,
    /**
     * I/O error.
     */
    MbusErrIoError,
    /**
     * Unexpected error.
     */
    MbusErrUnexpected,
    /**
     * Connection lost.
     */
    MbusErrConnectionLost,
    /**
     * Unsupported function.
     */
    MbusErrUnsupportedFunction,
    /**
     * Reserved sub-function.
     */
    MbusErrReservedSubFunction,
    /**
     * Invalid PDU length.
     */
    MbusErrInvalidPduLength,
    /**
     * Invalid ADU length.
     */
    MbusErrInvalidAduLength,
    /**
     * Connection failed.
     */
    MbusErrConnectionFailed,
    /**
     * Connection closed.
     */
    MbusErrConnectionClosed,
    /**
     * Buffer too small.
     */
    MbusErrBufferTooSmall,
    /**
     * Buffer length mismatch.
     */
    MbusErrBufferLenMismatch,
    /**
     * Send failed.
     */
    MbusErrSendFailed,
    /**
     * Invalid address.
     */
    MbusErrInvalidAddress,
    /**
     * Invalid offset.
     */
    MbusErrInvalidOffset,
    /**
     * Too many in-flight requests.
     */
    MbusErrTooManyRequests,
    /**
     * Invalid function code.
     */
    MbusErrInvalidFunctionCode,
    /**
     * No retries left.
     */
    MbusErrNoRetriesLeft,
    /**
     * Too many file read sub-requests.
     */
    MbusErrTooManyFileReadSubRequests,
    /**
     * File read PDU overflow.
     */
    MbusErrFileReadPduOverflow,
    /**
     * Unexpected response.
     */
    MbusErrUnexpectedResponse,
    /**
     * Invalid transport.
     */
    MbusErrInvalidTransport,
    /**
     * Invalid slave address.
     */
    MbusErrInvalidSlaveAddress,
    /**
     * Checksum error.
     */
    MbusErrChecksumError,
    /**
     * Invalid configuration.
     */
    MbusErrInvalidConfiguration,
    /**
     * Invalid number of expected responses.
     */
    MbusErrInvalidNumOfExpectedRsps,
    /**
     * Invalid data length.
     */
    MbusErrInvalidDataLen,
    /**
     * Invalid quantity.
     */
    MbusErrInvalidQuantity,
    /**
     * Invalid value.
     */
    MbusErrInvalidValue,
    /**
     * Invalid AND mask.
     */
    MbusErrInvalidAndMask,
    /**
     * Invalid OR mask.
     */
    MbusErrInvalidOrMask,
    /**
     * Invalid byte count.
     */
    MbusErrInvalidByteCount,
    /**
     * Invalid device identification.
     */
    MbusErrInvalidDeviceIdentification,
    /**
     * Invalid device ID code.
     */
    MbusErrInvalidDeviceIdCode,
    /**
     * Invalid MEI type.
     */
    MbusErrInvalidMeiType,
    /**
     * Invalid broadcast address.
     */
    MbusErrInvalidBroadcastAddress,
    /**
     * Broadcast not allowed.
     */
    MbusErrBroadcastNotAllowed,
    /**
     * Framing error (protocol timing violation).
     */
    MbusErrFramingError,
    /**
     * Null pointer passed.
     */
    MbusErrNullPointer,
    /**
     * Invalid UTF-8 string.
     */
    MbusErrInvalidUtf8,
    /**
     * Invalid client ID (freed or never allocated).
     */
    MbusErrInvalidClientId,
    /**
     * Client pool is full — no free slots.
     */
    MbusErrPoolFull,
    /**
     * Client type mismatch (e.g. TCP call on serial ID).
     */
    MbusErrClientTypeMismatch,
    /**
     * Client is busy (indicates an illegal re-entrant call from a callback).
     */
    MbusErrBusy,
} MbusStatusCode;

/**
 * Exception code returned by every C server callback.
 *
 * Maps 1-to-1 with the Modbus standard exception codes:
 *
 * | Value | Name | When to return |
 * |-------|------|----------------|
 * | `0` | `Ok` | Request handled successfully. The server sends a normal response. |
 * | `1` | `IllegalFunction` | This function code is not supported by your server implementation. |
 * | `2` | `IllegalDataAddress` | The requested `address` or `quantity` is outside the server's valid range. |
 * | `3` | `IllegalDataValue` | A value in the request data field is not acceptable (e.g. out-of-range register value). |
 * | `4` | `ServerDeviceFailure` | An unrecoverable error occurred while processing the request (hardware fault, internal error). |
 *
 * # Notes
 * - `Ok = 0` is a **non-standard sentinel** used only by this C API.  It is
 *   never sent on the wire; the server translates it to a normal success response.
 * - For **write** function codes (FC05, FC06, FC0F, FC10, FC15, FC16, FC17),
 *   `Ok` means the write was accepted and committed.  The server echoes the
 *   request back to the master as specified by the Modbus protocol.
 * - For **read** function codes (FC01–FC04, FC07, FC0B, FC0C, FC11, FC14, FC17,
 *   FC18, FC2B), `Ok` means the `out_*` fields have been populated with valid
 *   response data.
 * - If you detect a timing violation in application logic (e.g. a sensor timed
 *   out), return `ServerDeviceFailure`; do **not** return `FramingError` — that
 *   is a transport-level status only returned by the `recv` callback.
 */
typedef enum MbusServerExceptionCode {
    /**
     * No exception — the callback handled the request successfully.
     */
    Ok = 0,
    /**
     * FC is not supported / not implemented by this server.
     */
    IllegalFunction = 1,
    /**
     * Address or offset is outside the server's valid range.
     */
    IllegalDataAddress = 2,
    /**
     * A data value in the request is not acceptable.
     */
    IllegalDataValue = 3,
    /**
     * The server could not complete the request due to an internal failure.
     */
    ServerDeviceFailure = 4,
} MbusServerExceptionCode;

/**
 * Server ID type: an opaque `u16` index into one of the server sub-pools.
 */
typedef uint16_t MbusServerId;

/**
 * C-provided transport callbacks — the only interface between C code and the Rust Modbus stack.
 *
 * Fill in this struct and pass it to a `mbus_*_new` constructor.  The Rust stack
 * calls these function pointers whenever it needs to open, close, send data, or
 * receive data over the underlying physical medium (TCP socket, UART, etc.).
 *
 * # Requirements
 *
 * - **All five callbacks must be non-`NULL`.**  `validate_transport_callbacks` checks
 *   this; constructors reject a struct with any `NULL` slot.
 * - Every callback receives the same `userdata` pointer that is stored in this struct.
 *   Use it to pass your driver state (file descriptor, hardware register base, etc.).
 * - Callbacks may be called from any context that calls `mbus_*_poll`, `mbus_*_connect`,
 *   or `mbus_*_send`.  If you use locking in your driver, acquire and release the lock
 *   inside the callback — do **not** hold an external lock while polling.
 * - Callbacks must **never** call back into the Modbus stack (no `mbus_*` functions
 *   from inside a callback) — doing so causes re-entrant undefined behaviour.
 *
 * # Lifetime
 *
 * The struct (and everything `userdata` points to) must remain valid until
 * `mbus_*_free` is called on every server or client that uses it.
 *
 * # Minimal example (C, TCP)
 *
 * ```c
 * static MbusStatusCode my_connect(void *ud) {
 *     MyCtx *ctx = (MyCtx *)ud;
 *     ctx->fd = socket_open(ctx->host, ctx->port);
 *     return ctx->fd >= 0 ? MBUS_OK : MBUS_ERR_CONNECTION_FAILED;
 * }
 * static MbusStatusCode my_disconnect(void *ud) {
 *     socket_close(((MyCtx *)ud)->fd);
 *     return MBUS_OK;
 * }
 * static MbusStatusCode my_send(const uint8_t *data, uint16_t len, void *ud) {
 *     return socket_write(((MyCtx *)ud)->fd, data, len) == len
 *         ? MBUS_OK : MBUS_ERR_SEND_FAILED;
 * }
 * static MbusStatusCode my_recv(uint8_t *buf, uint16_t cap,
 *                               uint16_t *out_len, void *ud) {
 *     int n = socket_read_nonblocking(((MyCtx *)ud)->fd, buf, cap);
 *     if (n > 0) { *out_len = (uint16_t)n; return MBUS_OK; }
 *     return n == 0 ? MBUS_ERR_TIMEOUT : MBUS_ERR_IO_ERROR;
 * }
 * static uint8_t my_is_connected(void *ud) {
 *     return ((MyCtx *)ud)->fd >= 0 ? 1 : 0;
 * }
 *
 * static MbusTransportCallbacks g_transport = {
 *     .userdata       = &g_ctx,
 *     .on_connect     = my_connect,
 *     .on_disconnect  = my_disconnect,
 *     .on_send        = my_send,
 *     .on_recv        = my_recv,
 *     .on_is_connected = my_is_connected,
 * };
 * ```
 */
typedef struct MbusTransportCallbacks {
    /**
     * Opaque pointer passed unchanged to every callback invocation.
     *
     * Typically points to your driver context struct (file descriptor, register
     * base address, mutex handle, etc.).  May be `NULL` if your callbacks do not
     * need per-instance state (e.g. a singleton UART driver).
     */
    void *userdata;
    /**
     * Open the physical connection.
     *
     * Called once by `mbus_*_connect`.  The stack does not call `on_send` or
     * `on_recv` until this returns `MBUS_OK`.
     *
     * # What to do
     * - Open the socket / serial port / SPI bus.
     * - Perform any hardware initialisation (baud rate, parity, stop bits).
     * - For serial servers: configure the UART but do **not** start receiving
     *   until you return — the stack will call `on_recv` on the first poll.
     *
     * # Return values
     * | Code | Meaning |
     * |------|---------|
     * | `MBUS_OK` | Connection established; stack proceeds normally. |
     * | `MBUS_ERR_CONNECTION_FAILED` | Could not open the port/socket (e.g. ENOENT, EACCES). |
     * | `MBUS_ERR_IO_ERROR` | Low-level I/O failure during hardware setup. |
     * | `MBUS_ERR_INVALID_CONFIGURATION` | Supplied config is not supported by this hardware. |
     *
     * Any other non-`MBUS_OK` code is mapped to `MbusError::Unexpected` internally.
     */
    enum MbusStatusCode (*on_connect)(void *userdata);
    /**
     * Close the physical connection.
     *
     * Called by `mbus_*_disconnect` and during server teardown.  After this
     * returns, the stack will not call `on_send` or `on_recv` until
     * `on_connect` is called again.
     *
     * # What to do
     * - Release the socket / serial port file descriptor.
     * - For RS-485: de-assert the transmit-enable line if your driver holds it.
     * - This function should be idempotent — calling it on an already-closed
     *   transport must not crash or return an error.
     *
     * # Return values
     * | Code | Meaning |
     * |------|---------|
     * | `MBUS_OK` | Disconnected successfully (or was already disconnected). |
     * | `MBUS_ERR_IO_ERROR` | An error occurred while flushing or closing the port. |
     *
     * The return value is checked but not acted upon by the stack beyond logging.
     */
    enum MbusStatusCode (*on_disconnect)(void *userdata);
    /**
     * Write a complete Modbus ADU frame to the medium.
     *
     * The stack calls this once per outgoing frame with a fully-formed byte
     * slice (`data[0..len]`).  The function must write **all** `len` bytes
     * atomically from the stack's perspective — partial writes are not retried
     * at the byte level.
     *
     * # Parameters
     * - `data`     — Pointer to the frame bytes.  Valid only for the duration
     *   of this call; do not retain it.
     * - `len`      — Number of bytes to send (always ≤ `MAX_ADU_FRAME_LEN` = 256).
     * - `userdata` — The value stored in `MbusTransportCallbacks::userdata`.
     *
     * # RS-485 / half-duplex requirement
     * Assert the TX-enable line **before** writing the first byte and
     * de-assert it **after** the last byte has been shifted out of the UART
     * FIFO (not just after the write syscall returns).  Failing to do this
     * corrupts the frame from the perspective of other nodes on the bus.
     *
     * # Return values
     * | Code | Meaning |
     * |------|---------|
     * | `MBUS_OK` | All bytes written successfully. |
     * | `MBUS_ERR_SEND_FAILED` | Write failed partway through (broken pipe, UART overflow). |
     * | `MBUS_ERR_IO_ERROR` | Hardware-level I/O error (DMA fault, framing error on TX). |
     * | `MBUS_ERR_CONNECTION_CLOSED` | The remote end closed the connection (TCP only). |
     *
     * On failure the stack queues the frame for retry (up to `max_send_retries`).
     */
    enum MbusStatusCode (*on_send)(const uint8_t *data, uint16_t len, void *userdata);
    /**
     * Read the next available Modbus ADU frame from the medium.
     *
     * The stack calls this once per `mbus_*_poll` invocation.  The function
     * must be **non-blocking** (or use a very short read timeout) so that the
     * poll loop remains responsive.
     *
     * # Parameters
     * - `buffer`     — Rust-allocated scratch buffer; write received bytes here.
     *   Valid only for the duration of this call.
     * - `buffer_cap` — Capacity of `buffer` in bytes (always `MAX_ADU_FRAME_LEN` = 256).
     *   Never write more than `buffer_cap` bytes.
     * - `out_len`    — Write the number of bytes placed in `buffer` here.
     *   Must be set to `0` when returning anything other than `MBUS_OK`.
     * - `userdata`   — The value stored in `MbusTransportCallbacks::userdata`.
     *
     * # TCP / stream transports
     * Read as many bytes as are available right now (non-blocking).  The Rust
     * layer uses a sliding window to assemble complete frames from partial reads;
     * you do not need to wait for a full frame.
     *
     * # Serial RTU transports — timing requirements
     * The `on_recv` callback is the correct place to enforce Modbus
     * inter-character timing (§2.5 of the Modbus Serial Line Specification):
     *
     * - **t3.5 (end-of-frame):** Wait until the line has been silent for at
     *   least 3.5 character times after the last received byte.  Only then
     *   return the accumulated bytes with `MBUS_OK`.  This ensures each
     *   `on_recv` call delivers exactly one complete frame.
     *
     * - **t1.5 (framing violation):** If silence of ≥ 1.5 character times is
     *   detected *between* bytes of the same frame, the frame is corrupt.
     *   Return **`MBUS_ERR_FRAMING_ERROR`** immediately.  The stack will:
     *     1. Discard all bytes buffered so far.
     *     2. Keep the transport connected.
     *     3. Resume waiting for a clean frame on the next poll.
     *
     * # Return values
     * | Code | Meaning |
     * |------|---------|
     * | `MBUS_OK` | Frame bytes written into `buffer`; `*out_len > 0`. |
     * | `MBUS_ERR_TIMEOUT` | No data available this poll (bus idle / no client request yet). The stack skips processing and polls again. |
     * | `MBUS_ERR_FRAMING_ERROR` | **Serial only.** t1.5 inter-character gap detected mid-frame. Stack discards the partial frame and continues. |
     * | `MBUS_ERR_IO_ERROR` | Hardware read error (UART overrun, DMA fault). Stack marks the transport as disconnected. |
     * | `MBUS_ERR_CONNECTION_CLOSED` | Remote closed the connection (TCP) or the port was unexpectedly closed. Stack disconnects and stops polling. |
     * | `MBUS_ERR_CONNECTION_LOST` | Connection dropped unexpectedly (e.g. TCP RST). Same effect as `CONNECTION_CLOSED`. |
     * | `MBUS_ERR_BUFFER_TOO_SMALL` | Frame exceeded `buffer_cap`. Stack discards data (should not happen under normal conditions). |
     *
     * **Do not** set `*out_len` to a non-zero value when returning an error code —
     * the stack ignores `buffer` contents on any non-`MBUS_OK` return.
     */
    enum MbusStatusCode (*on_recv)(uint8_t *buffer,
                                   uint16_t buffer_cap,
                                   uint16_t *out_len,
                                   void *userdata);
    /**
     * Query whether the transport is currently open/connected.
     *
     * Called by `mbus_*_is_connected` and internally after a recv/send error
     * to decide whether to attempt a reconnect.
     *
     * # What to do
     * - Return `1` (non-zero) if the port or socket is open and ready for I/O.
     * - Return `0` if the transport has been closed, has not yet been opened,
     *   or is in an error state.
     * - This function must be **side-effect-free** and **cheap** — it may be
     *   called multiple times per poll cycle.
     *
     * # Return values
     * | Value | Meaning |
     * |-------|---------|
     * | `1` (or any non-zero) | Transport is open and ready. |
     * | `0` | Transport is closed or in error. |
     */
    uint8_t (*on_is_connected)(void *userdata);
} MbusTransportCallbacks;

/**
 * Request context for FC 0x01 — Read Coils.
 *
 * C reads `address` and `quantity`; writes packed coil bits into `out_data` (at most
 * `out_data_len` bytes) and sets `out_byte_count` to the number of bytes written.
 */
typedef struct MbusServerReadCoilsReq {
    /**
     * Slave/unit address of the request.
     */
    uint8_t unit_id;
    /**
     * Transaction ID (MBAP) or 0 for serial.
     */
    uint16_t txn_id;
    /**
     * Starting coil address.
     */
    uint16_t address;
    /**
     * Number of coils to read.
     */
    uint16_t quantity;
    /**
     * Buffer to write packed coil bytes into (Rust-allocated, valid for callback duration).
     */
    uint8_t *out_data;
    /**
     * Capacity of `out_data` in bytes.
     */
    uintptr_t out_data_len;
    /**
     * C must set this to the number of bytes written into `out_data`.
     */
    uint8_t out_byte_count;
} MbusServerReadCoilsReq;

/**
 * C callback type for FC 0x01.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadCoilsFn)(struct MbusServerReadCoilsReq *req,
                                                              void *userdata);

/**
 * Request context for FC 0x05 — Write Single Coil.
 */
typedef struct MbusServerWriteSingleCoilReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    /**
     * `true` = force coil ON, `false` = force coil OFF.
     */
    bool value;
} MbusServerWriteSingleCoilReq;

/**
 * C callback type for FC 0x05.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteSingleCoilFn)(const struct MbusServerWriteSingleCoilReq *req,
                                                                    void *userdata);

/**
 * Request context for FC 0x0F — Write Multiple Coils.
 *
 * `values` is a packed bit array from the master (LSB of first byte = coil at
 * `starting_address`). Valid for the duration of the callback only.
 */
typedef struct MbusServerWriteMultipleCoilsReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t starting_address;
    uint16_t quantity;
    /**
     * Packed coil bits from the master (read-only, valid for callback duration).
     */
    const uint8_t *values;
    /**
     * Number of bytes in `values`.
     */
    uintptr_t values_len;
} MbusServerWriteMultipleCoilsReq;

/**
 * C callback type for FC 0x0F.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteMultipleCoilsFn)(const struct MbusServerWriteMultipleCoilsReq *req,
                                                                       void *userdata);

/**
 * Request context for FC 0x02 — Read Discrete Inputs.
 */
typedef struct MbusServerReadDiscreteInputsReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    uint16_t quantity;
    uint8_t *out_data;
    uintptr_t out_data_len;
    uint8_t out_byte_count;
} MbusServerReadDiscreteInputsReq;

/**
 * C callback type for FC 0x02.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadDiscreteInputsFn)(struct MbusServerReadDiscreteInputsReq *req,
                                                                       void *userdata);

/**
 * Request context for FC 0x03 — Read Holding Registers.
 *
 * `out_data` receives big-endian register bytes (2 bytes per register).
 * `out_byte_count` must be set to `quantity * 2` on success.
 */
typedef struct MbusServerReadHoldingRegistersReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    uint16_t quantity;
    uint8_t *out_data;
    uintptr_t out_data_len;
    uint8_t out_byte_count;
} MbusServerReadHoldingRegistersReq;

/**
 * C callback type for FC 0x03.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadHoldingRegistersFn)(struct MbusServerReadHoldingRegistersReq *req,
                                                                         void *userdata);

/**
 * Request context for FC 0x06 — Write Single Register.
 */
typedef struct MbusServerWriteSingleRegisterReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    uint16_t value;
} MbusServerWriteSingleRegisterReq;

/**
 * C callback type for FC 0x06.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteSingleRegisterFn)(const struct MbusServerWriteSingleRegisterReq *req,
                                                                        void *userdata);

/**
 * Request context for FC 0x10 — Write Multiple Registers.
 *
 * `values` contains the decoded `u16` register values (big-endian already parsed).
 * Valid for the duration of the callback only.
 */
typedef struct MbusServerWriteMultipleRegistersReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t starting_address;
    /**
     * Decoded register values from the master (read-only, valid for callback duration).
     */
    const uint16_t *values;
    /**
     * Number of elements in `values`.
     */
    uintptr_t values_len;
} MbusServerWriteMultipleRegistersReq;

/**
 * C callback type for FC 0x10.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteMultipleRegistersFn)(const struct MbusServerWriteMultipleRegistersReq *req,
                                                                           void *userdata);

/**
 * Request context for FC 0x16 — Mask Write Register.
 */
typedef struct MbusServerMaskWriteRegisterReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    uint16_t and_mask;
    uint16_t or_mask;
} MbusServerMaskWriteRegisterReq;

/**
 * C callback type for FC 0x16.
 */
typedef enum MbusServerExceptionCode (*MbusServerMaskWriteRegisterFn)(const struct MbusServerMaskWriteRegisterReq *req,
                                                                      void *userdata);

/**
 * Request context for FC 0x17 — Read/Write Multiple Registers.
 *
 * C writes the read result into `out_data` (big-endian register bytes) and sets
 * `out_byte_count`. `write_values` contains the decoded write values from the master.
 */
typedef struct MbusServerReadWriteMultipleRegistersReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t read_address;
    uint16_t read_quantity;
    uint16_t write_address;
    /**
     * Decoded write values from the master (read-only, valid for callback duration).
     */
    const uint16_t *write_values;
    uintptr_t write_values_len;
    uint8_t *out_data;
    uintptr_t out_data_len;
    /**
     * C must set to the number of bytes written into `out_data`.
     */
    uint8_t out_byte_count;
} MbusServerReadWriteMultipleRegistersReq;

/**
 * C callback type for FC 0x17.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadWriteMultipleRegistersFn)(struct MbusServerReadWriteMultipleRegistersReq *req,
                                                                               void *userdata);

/**
 * Request context for FC 0x04 — Read Input Registers.
 */
typedef struct MbusServerReadInputRegistersReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t address;
    uint16_t quantity;
    uint8_t *out_data;
    uintptr_t out_data_len;
    uint8_t out_byte_count;
} MbusServerReadInputRegistersReq;

/**
 * C callback type for FC 0x04.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadInputRegistersFn)(struct MbusServerReadInputRegistersReq *req,
                                                                       void *userdata);

/**
 * Request context for FC 0x18 — Read FIFO Queue.
 */
typedef struct MbusServerReadFifoQueueReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t pointer_address;
    uint8_t *out_data;
    uintptr_t out_data_len;
    /**
     * C must set to the number of bytes written.
     */
    uint8_t out_byte_count;
} MbusServerReadFifoQueueReq;

/**
 * C callback type for FC 0x18.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadFifoQueueFn)(struct MbusServerReadFifoQueueReq *req,
                                                                  void *userdata);

/**
 * Request context for FC 0x14 — Read File Record (one sub-request at a time).
 *
 * C writes record data bytes into `out_data` and sets `out_byte_count`.
 */
typedef struct MbusServerReadFileRecordReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t file_number;
    uint16_t record_number;
    uint16_t record_length;
    uint8_t *out_data;
    uintptr_t out_data_len;
    /**
     * C must set to the number of bytes written into `out_data`.
     */
    uint8_t out_byte_count;
} MbusServerReadFileRecordReq;

/**
 * C callback type for FC 0x14.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadFileRecordFn)(struct MbusServerReadFileRecordReq *req,
                                                                   void *userdata);

/**
 * Request context for FC 0x15 — Write File Record (one sub-request at a time).
 *
 * `record_data` contains decoded `u16` words. Valid for the callback duration only.
 */
typedef struct MbusServerWriteFileRecordReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint16_t file_number;
    uint16_t record_number;
    uint16_t record_length;
    /**
     * Decoded record data words (read-only, valid for callback duration).
     */
    const uint16_t *record_data;
    uintptr_t record_data_len;
} MbusServerWriteFileRecordReq;

/**
 * C callback type for FC 0x15.
 */
typedef enum MbusServerExceptionCode (*MbusServerWriteFileRecordFn)(const struct MbusServerWriteFileRecordReq *req,
                                                                    void *userdata);

/**
 * Request context for FC 0x07 — Read Exception Status.
 *
 * C sets `out_status` to the 8-bit exception status byte.
 */
typedef struct MbusServerReadExceptionStatusReq {
    uint8_t unit_id;
    uint16_t txn_id;
    /**
     * C must set this to the 8-bit exception status byte.
     */
    uint8_t out_status;
} MbusServerReadExceptionStatusReq;

/**
 * C callback type for FC 0x07.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadExceptionStatusFn)(struct MbusServerReadExceptionStatusReq *req,
                                                                        void *userdata);

/**
 * Request context for FC 0x08 — Diagnostics.
 *
 * `sub_function` is the raw 16-bit sub-function code (see Modbus spec §6.8).
 * C sets `out_result` to the 16-bit data echo/result.
 */
typedef struct MbusServerDiagnosticsReq {
    uint8_t unit_id;
    uint16_t txn_id;
    /**
     * Raw sub-function code (e.g. 0x0000 = Return Query Data, 0x0002 = Return Diagnostic Register).
     */
    uint16_t sub_function;
    /**
     * Data word from the request.
     */
    uint16_t data;
    /**
     * C must set this to the 16-bit result/echo value.
     */
    uint16_t out_result;
} MbusServerDiagnosticsReq;

/**
 * C callback type for FC 0x08.
 */
typedef enum MbusServerExceptionCode (*MbusServerDiagnosticsFn)(struct MbusServerDiagnosticsReq *req,
                                                                void *userdata);

/**
 * Request context for FC 0x0B — Get Comm Event Counter.
 *
 * C sets `out_status` (status word) and `out_event_count`.
 */
typedef struct MbusServerGetCommEventCounterReq {
    uint8_t unit_id;
    uint16_t txn_id;
    /**
     * C must set this to the status word.
     */
    uint16_t out_status;
    /**
     * C must set this to the event counter value.
     */
    uint16_t out_event_count;
} MbusServerGetCommEventCounterReq;

/**
 * C callback type for FC 0x0B.
 */
typedef enum MbusServerExceptionCode (*MbusServerGetCommEventCounterFn)(struct MbusServerGetCommEventCounterReq *req,
                                                                        void *userdata);

/**
 * Request context for FC 0x0C — Get Comm Event Log.
 *
 * C writes event bytes into `out_events` (max `out_events_len` bytes) and
 * sets the four output scalar fields.
 */
typedef struct MbusServerGetCommEventLogReq {
    uint8_t unit_id;
    uint16_t txn_id;
    /**
     * Buffer for event log bytes (Rust-allocated, valid for callback duration).
     */
    uint8_t *out_events;
    /**
     * Capacity of `out_events`.
     */
    uintptr_t out_events_len;
    /**
     * C must set to the Status word.
     */
    uint16_t out_status;
    /**
     * C must set to the Event Count.
     */
    uint16_t out_event_count;
    /**
     * C must set to the Message Count.
     */
    uint16_t out_message_count;
    /**
     * C must set to the number of events written into `out_events`.
     */
    uint8_t out_num_events;
} MbusServerGetCommEventLogReq;

/**
 * C callback type for FC 0x0C.
 */
typedef enum MbusServerExceptionCode (*MbusServerGetCommEventLogFn)(struct MbusServerGetCommEventLogReq *req,
                                                                    void *userdata);

/**
 * Request context for FC 0x11 — Report Server ID.
 *
 * C writes vendor/device identification bytes into `out_server_id` and sets
 * `out_byte_count` and `out_run_indicator_status`.
 */
typedef struct MbusServerReportServerIdReq {
    uint8_t unit_id;
    uint16_t txn_id;
    /**
     * Buffer for server ID bytes (Rust-allocated).
     */
    uint8_t *out_server_id;
    /**
     * Capacity of `out_server_id`.
     */
    uintptr_t out_server_id_len;
    /**
     * C must set to the number of Server ID bytes written.
     */
    uint8_t out_byte_count;
    /**
     * C must set to the Run Indicator Status byte (0x00 = OFF, 0xFF = ON).
     */
    uint8_t out_run_indicator_status;
} MbusServerReportServerIdReq;

/**
 * C callback type for FC 0x11.
 */
typedef enum MbusServerExceptionCode (*MbusServerReportServerIdFn)(struct MbusServerReportServerIdReq *req,
                                                                   void *userdata);

/**
 * Request context for FC 0x2B / MEI 0x0E — Read Device Identification.
 *
 * C writes object data into `out_data` and sets all `out_*` fields.
 */
typedef struct MbusServerReadDeviceIdentificationReq {
    uint8_t unit_id;
    uint16_t txn_id;
    uint8_t read_device_id_code;
    uint8_t start_object_id;
    uint8_t *out_data;
    uintptr_t out_data_len;
    /**
     * C must set to the conformity level byte.
     */
    uint8_t out_conformity_level;
    /**
     * C must set to the "more follows" object ID (0x00 if none).
     */
    uint8_t out_more_follows_object_id;
    /**
     * C must set to `true` if more objects follow (segmentation).
     */
    bool out_has_more;
    /**
     * C must set to the next Object ID to request (only valid when `out_has_more` is true).
     */
    uint8_t out_next_object_id;
    /**
     * C must set to the number of bytes written into `out_data`.
     */
    uint8_t out_byte_count;
} MbusServerReadDeviceIdentificationReq;

/**
 * C callback type for FC 0x2B / MEI 0x0E.
 */
typedef enum MbusServerExceptionCode (*MbusServerReadDeviceIdentificationFn)(struct MbusServerReadDeviceIdentificationReq *req,
                                                                             void *userdata);

/**
 * Master callback table for a C Modbus server application.
 *
 * Pass a populated instance to `mbus_tcp_server_new`,
 * `mbus_serial_rtu_server_new`, or `mbus_serial_ascii_server_new`.
 *
 * ## NULL slots
 * Any callback slot left as `NULL` causes the server to respond with
 * `ExceptionCode::IllegalFunction` (0x01) for that function code.
 * You do not need to implement callbacks for function codes your device
 * does not support.
 *
 * ## Return value contract
 * Every callback returns `MbusServerExceptionCode`.  The server uses this to
 * decide what to send on the wire:
 *
 * | Return value | Wire response |
 * |---|---|
 * | `Ok` | Normal success response (echo or `out_*` data). |
 * | `IllegalFunction` | Exception response 0x01. |
 * | `IllegalDataAddress` | Exception response 0x02. |
 * | `IllegalDataValue` | Exception response 0x03. |
 * | `ServerDeviceFailure` | Exception response 0x04. |
 *
 * ## Timing — serial servers
 * Callbacks are invoked from within `mbus_serial_server_poll`.  The stack
 * does **not** call the `recv` callback while a callback is running, so you
 * cannot observe a t1.5/t3.5 violation from inside a handler.  Timing
 * violations are detected and reported exclusively through the `recv`
 * transport callback before dispatch (see the `serial_server` module docs).
 *
 * ## Lifetime of pointer fields
 * All `*mut` and `*const` pointer fields in the `*Req` structs are valid only
 * for the duration of the callback invocation.  Do **not** retain them.
 *
 * ## Example (C)
 *
 * ```c
 * static MbusServerHandlers g_handlers = {
 *     .userdata             = &my_app_state,
 *     .on_read_holding_registers = my_read_hr_handler,
 *     .on_write_single_register  = my_write_sr_handler,
 *     // All other slots are NULL → server returns IllegalFunction.
 * };
 * ```
 */
typedef struct MbusServerHandlers {
    /**
     * Opaque pointer passed to every callback.
     */
    void *userdata;
    MbusServerReadCoilsFn on_read_coils;
    MbusServerWriteSingleCoilFn on_write_single_coil;
    MbusServerWriteMultipleCoilsFn on_write_multiple_coils;
    MbusServerReadDiscreteInputsFn on_read_discrete_inputs;
    MbusServerReadHoldingRegistersFn on_read_holding_registers;
    MbusServerWriteSingleRegisterFn on_write_single_register;
    MbusServerWriteMultipleRegistersFn on_write_multiple_registers;
    MbusServerMaskWriteRegisterFn on_mask_write_register;
    MbusServerReadWriteMultipleRegistersFn on_read_write_multiple_registers;
    MbusServerReadInputRegistersFn on_read_input_registers;
    MbusServerReadFifoQueueFn on_read_fifo_queue;
    MbusServerReadFileRecordFn on_read_file_record;
    MbusServerWriteFileRecordFn on_write_file_record;
    MbusServerReadExceptionStatusFn on_read_exception_status;
    MbusServerDiagnosticsFn on_diagnostics;
    MbusServerGetCommEventCounterFn on_get_comm_event_counter;
    MbusServerGetCommEventLogFn on_get_comm_event_log;
    MbusServerReportServerIdFn on_report_server_id;
    MbusServerReadDeviceIdentificationFn on_read_device_identification;
} MbusServerHandlers;

/**
 * Common server configuration shared by TCP and Serial server types.
 *
 * Only fields that influence the server runtime logic are included here;
 * transport-level details (host address, port, baud rate) are handled
 * separately in the `_new` constructor callbacks.
 */
typedef struct MbusServerConfig {
    /**
     * Slave/unit address this server will respond to.  Valid range: 1–247.
     * For TCP-only deployments the conventional value is 1 or 0xFF.
     */
    uint8_t slave_address;
    /**
     * Maximum time (ms) allocated to process and respond to a single request.
     * Passed to `ResilienceConfig::default()` for now; reserved for future
     * per-request timeout enforcement.
     */
    uint32_t response_timeout_ms;
} MbusServerConfig;

/**
 * Observability callbacks delivered by the gateway.
 *
 * Pass a populated value to [`mbus_gateway_new`](super::gateway::mbus_gateway_new).
 * Any field set to `None` (`NULL` from C) is treated as a no-op.
 */
typedef struct MbusGatewayCallbacks {
    /**
     * Opaque user pointer threaded to every callback.
     */
    void *userdata;
    /**
     * Called after a request has been forwarded to a downstream channel.
     */
    void (*on_forward)(uint8_t session_id, uint8_t unit_id, uint16_t channel_idx, void *userdata);
    /**
     * Called after a response has been delivered to the upstream client.
     */
    void (*on_response_returned)(uint8_t session_id, uint16_t upstream_txn, void *userdata);
    /**
     * Called when no downstream route was found for a unit ID.
     */
    void (*on_routing_miss)(uint8_t session_id, uint8_t unit_id, void *userdata);
    /**
     * Called when a downstream device failed to respond before timeout.
     */
    void (*on_downstream_timeout)(uint8_t session_id, uint16_t internal_txn, void *userdata);
    /**
     * Called when the upstream session disconnects (transport-level error).
     */
    void (*on_upstream_disconnect)(uint8_t session_id, void *userdata);
} MbusGatewayCallbacks;

/**
 * Opaque gateway handle. `MBUS_INVALID_GATEWAY_ID` (0xFF) is the sentinel.
 */
typedef uint8_t MbusGatewayId;
    /**
     * Starting record number within the file (0–9999).
     */
    uint16_t record_number;
    /**
     * Number of 16-bit registers. For reads: how many to read; for writes: must equal `data_len`.
     */
    uint16_t record_length;
    /**
     * Pointer to write data (`null` for reads).
     */
    const uint16_t *data;
    /**
     * Number of valid words pointed to by `data` (0 for reads).
     */
    uint16_t data_len;
    /**
     * Starting record number within the file (0–9999).
     */
    uint16_t record_number;
    /**
     * Number of 16-bit registers. For reads: how many to read; for writes: must equal `data_len`.
     */
    uint16_t record_length;
    /**
     * Pointer to write data (`null` for reads). Valid for at least `data_len` words.
     */
    const uint16_t *data;
    /**
     * Number of valid words pointed to by `data` (0 for reads).
     */
    uint16_t data_len;
    /**
     * `fn(ctx, address, count, out_packed_bytes, out_byte_count) -> i32`
     */
    int32_t (*read_coils)(void*, uint16_t, uint16_t, uint8_t*, uint16_t*);
    /**
     * `fn(ctx, address, value_bool) -> i32`
     */
    int32_t (*write_single_coil)(void*, uint16_t, uint8_t);
    /**
     * `fn(ctx, address, packed_bytes, byte_count, coil_count) -> i32`
     */
    int32_t (*write_multiple_coils)(void*, uint16_t, const uint8_t*, uint16_t, uint16_t);
    /**
     * `fn(ctx, address, count, out_packed_bytes, out_byte_count) -> i32`
     */
    int32_t (*read_discrete_inputs)(void*, uint16_t, uint16_t, uint8_t*, uint16_t*);
    /**
     * `fn(ctx, address, count, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_holding_registers)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, address, count, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_input_registers)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, address, value) -> i32`
     */
    int32_t (*write_single_register)(void*, uint16_t, uint16_t);
    /**
     * `fn(ctx, address, values_be_bytes, count) -> i32`
     */
    int32_t (*write_multiple_registers)(void*, uint16_t, const uint8_t*, uint16_t);
    /**
     * `fn(ctx, address, and_mask, or_mask) -> i32`
     */
    int32_t (*mask_write_register)(void*, uint16_t, uint16_t, uint16_t);
    /**
     * `fn(ctx, read_addr, read_count, write_addr, write_values_be_bytes,
     *    write_count, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_write_multiple_registers)(void*,
                                             uint16_t,
                                             uint16_t,
                                             uint16_t,
                                             const uint8_t*,
                                             uint16_t,
                                             uint16_t*,
                                             uint16_t*);
    /**
     * `fn(ctx, pointer_address, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_fifo_queue)(void*, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, out_status_byte) -> i32`
     */
    int32_t (*read_exception_status)(void*, uint8_t*);
    /**
     * `fn(ctx, sub_fn, data, out_sub_fn, out_data) -> i32`
     */
    int32_t (*diagnostics)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, out_status_word, out_event_count) -> i32`
     */
    int32_t (*get_comm_event_counter)(void*, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, out_payload_bytes, out_byte_count) -> i32`
     *
     * The payload must be formatted as:
     * `[status_hi, status_lo, event_count_hi, event_count_lo,
     *   msg_count_hi, msg_count_lo, event_bytes...]`
     */
    int32_t (*get_comm_event_log)(void*, uint8_t*, uint16_t*);
    /**
     * `fn(ctx, out_payload_bytes, out_byte_count) -> i32`
     */
    int32_t (*report_server_id)(void*, uint8_t*, uint16_t*);
    /**
     * Starting record number within the file (0–9999).
     */
    uint16_t record_number;
    /**
     * Number of 16-bit registers. For reads: how many to read; for writes: must equal `data_len`.
     */
    uint16_t record_length;
    /**
     * Pointer to write data (`null` for reads).
     */
    const uint16_t *data;
    /**
     * Number of valid words pointed to by `data` (0 for reads).
     */
    uint16_t data_len;
    /**
     * Starting record number within the file (0–9999).
     */
    uint16_t record_number;
    /**
     * Number of 16-bit registers. For reads: how many to read; for writes: must equal `data_len`.
     */
    uint16_t record_length;
    /**
     * Pointer to write data (`null` for reads). Valid for at least `data_len` words.
     */
    const uint16_t *data;
    /**
     * Number of valid words pointed to by `data` (0 for reads).
     */
    uint16_t data_len;
    /**
     * `fn(ctx, address, count, out_packed_bytes, out_byte_count) -> i32`
     */
    int32_t (*read_coils)(void*, uint16_t, uint16_t, uint8_t*, uint16_t*);
    /**
     * `fn(ctx, address, value_bool) -> i32`
     */
    int32_t (*write_single_coil)(void*, uint16_t, uint8_t);
    /**
     * `fn(ctx, address, packed_bytes, byte_count, coil_count) -> i32`
     */
    int32_t (*write_multiple_coils)(void*, uint16_t, const uint8_t*, uint16_t, uint16_t);
    /**
     * `fn(ctx, address, count, out_packed_bytes, out_byte_count) -> i32`
     */
    int32_t (*read_discrete_inputs)(void*, uint16_t, uint16_t, uint8_t*, uint16_t*);
    /**
     * `fn(ctx, address, count, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_holding_registers)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, address, count, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_input_registers)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, address, value) -> i32`
     */
    int32_t (*write_single_register)(void*, uint16_t, uint16_t);
    /**
     * `fn(ctx, address, values_be_bytes, count) -> i32`
     */
    int32_t (*write_multiple_registers)(void*, uint16_t, const uint8_t*, uint16_t);
    /**
     * `fn(ctx, address, and_mask, or_mask) -> i32`
     */
    int32_t (*mask_write_register)(void*, uint16_t, uint16_t, uint16_t);
    /**
     * `fn(ctx, read_addr, read_count, write_addr, write_values_be_bytes,
     *    write_count, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_write_multiple_registers)(void*,
                                             uint16_t,
                                             uint16_t,
                                             uint16_t,
                                             const uint8_t*,
                                             uint16_t,
                                             uint16_t*,
                                             uint16_t*);
    /**
     * `fn(ctx, pointer_address, out_u16_values, out_count) -> i32`
     */
    int32_t (*read_fifo_queue)(void*, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, out_status_byte) -> i32`
     */
    int32_t (*read_exception_status)(void*, uint8_t*);
    /**
     * `fn(ctx, sub_fn, data, out_sub_fn, out_data) -> i32`
     */
    int32_t (*diagnostics)(void*, uint16_t, uint16_t, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, out_status_word, out_event_count) -> i32`
     */
    int32_t (*get_comm_event_counter)(void*, uint16_t*, uint16_t*);
    /**
     * `fn(ctx, out_payload_bytes, out_byte_count) -> i32`
     *
     * The payload must be formatted as:
     * `[status_hi, status_lo, event_count_hi, event_count_lo,
     *   msg_count_hi, msg_count_lo, event_bytes...]`
     */
    int32_t (*get_comm_event_log)(void*, uint8_t*, uint16_t*);
    /**
     * `fn(ctx, out_payload_bytes, out_byte_count) -> i32`
     */
    int32_t (*report_server_id)(void*, uint8_t*, uint16_t*);

/**
 * Sentinel value meaning "no valid server" / creation failed.
 */
#define MBUS_INVALID_SERVER_ID 65535

/**
 * Sentinel "no valid gateway" value.
 */
#define MBUS_INVALID_GATEWAY_ID 255

/**
 * Returns a static null-terminated C string describing the status code.
 *
 * The returned pointer is always valid (points to a static string literal).
 * The caller must NOT free it.
 */
const char *mbus_status_str(enum MbusStatusCode code);

/**
 * No-op stub for pool lock (used when no external C caller provides it).
 */
void mbus_pool_lock(void);

/**
 * No-op stub for pool unlock.
 */
void mbus_pool_unlock(void);

/**
 * No-op stub for server lock.
 */
void mbus_server_lock(uint16_t _id);

/**
 * No-op stub for server unlock.
 */
void mbus_server_unlock(uint16_t _id);

/**
 * Lock the global pool (used only during client creation/destruction).
 */
extern void mbus_pool_lock(void);

/**
 * Unlock the global pool.
 */
extern void mbus_pool_unlock(void);

/**
 * Lock the global server pool (used only during server creation/destruction).
 */
extern void mbus_pool_lock(void);

/**
 * Unlock the global server pool.
 */
extern void mbus_pool_unlock(void);

/**
 * Lock a specific server instance.
 */
extern void mbus_server_lock(MbusServerId id);

/**
 * Unlock a specific server instance.
 */
extern void mbus_server_unlock(MbusServerId id);

/**
 * Creates a new Modbus Serial RTU server and returns an opaque server ID.
 *
 * # Parameters
 * - `transport` — Transport callbacks providing connect/disconnect/send/recv.
 *   The `recv` callback is responsible for t1.5/t3.5 silence detection (see
 *   the module-level timing section).
 * - `handlers`  — Application callback table. `NULL` slots automatically
 *   respond with `IllegalFunction` for that function code.
 * - `config`    — Server configuration (slave address, timeout).
 *
 * # Returns
 * A valid `MbusServerId` on success, or `MBUS_INVALID_SERVER_ID` on failure.
 *
 * `MBUS_INVALID_SERVER_ID` is returned when:
 * - Any pointer argument is `NULL`.
 * - Any required function pointer inside `transport` is `NULL`.
 * - `config.slave_address` is outside the valid range 1–247.
 * - The internal serial server pool is exhausted.
 *
 * # Safety
 * - `transport`, `handlers`, and `config` must remain valid for the entire
 *   lifetime of the server (until `mbus_serial_server_free` is called).
 * - All function pointers inside `transport` must be valid C functions.
 * - `handlers.userdata` must outlive the server.
 */
MbusServerId mbus_serial_rtu_server_new(const struct MbusTransportCallbacks *transport,
                                        const struct MbusServerHandlers *handlers,
                                        const struct MbusServerConfig *config);

/**
 * Destroys a Serial server and releases its pool slot.
 *
 * The server's transport is **not** automatically disconnected. Call
 * `mbus_serial_server_disconnect` first if the port may still be open.
 *
 * After this call, `id` becomes invalid and must not be reused.
 *
 * # Error conditions (no return value)
 * This function is infallible — an invalid or already-freed `id` is silently
 * ignored to simplify cleanup paths.
 */
void mbus_serial_server_free(MbusServerId id);

/**
 * Opens the serial server's transport (e.g. opens and configures the UART).
 *
 * Invokes the `connect` function-pointer from `MbusTransportCallbacks`.
 *
 * # Returns
 * - `MbusOk` — Port opened successfully.
 * - `MbusErrConnectionFailed` — The `connect` callback returned a failure
 *   (e.g. the serial port path does not exist, or permission denied).
 * - `MbusErrIoError` — A lower-level I/O error occurred while configuring
 *   the port (baud rate, parity, stop bits).
 * - `MbusErrInvalidConfiguration` — The transport rejected the supplied
 *   configuration (e.g. unsupported baud rate on this hardware).
 * - `MbusErrInvalidClientId` — `id` is not a valid serial server slot.
 *
 * The server lock must be held while calling this function.
 */
enum MbusStatusCode mbus_serial_server_connect(MbusServerId id);

/**
 * Closes the serial server's transport (e.g. releases the UART).
 *
 * Invokes the `disconnect` function-pointer from `MbusTransportCallbacks`.
 * Outstanding queued responses are discarded; the server pool slot remains
 * valid and can be reconnected with `mbus_serial_server_connect`.
 *
 * # Returns
 * - `MbusOk` — Port closed (or was already closed).
 * - `MbusErrInvalidClientId` — `id` is not a valid serial server slot.
 *
 * The server lock must be held while calling this function.
 */
enum MbusStatusCode mbus_serial_server_disconnect(MbusServerId id);

/**
 * Drives the serial server state machine for one iteration.
 *
 * Must be called in a tight loop or cooperative scheduler task. Each call:
 * 1. **Response retry** — resends queued responses from previous failed sends.
 * 2. **Receive** — calls the `recv` transport callback once to collect bytes.
 * 3. **Frame assembly** — appends received bytes to the internal sliding window.
 * 4. **Dispatch** — when a complete RTU/ASCII frame is recognised, the matching
 *    `MbusServerHandlers` callback is invoked.
 * 5. **Send** — transmits the response via the `send` transport callback.
 *
 * # Returns
 * This function always returns `MbusOk` for normal poll-loop operation.
 * Transport-level events are handled internally:
 *
 * | `recv` result | Server action |
 * |---------------|---------------|
 * | `MbusOk` | Bytes appended to the receive buffer; frame assembly continues. |
 * | `MbusErrTimeout` | No data available this poll; silently skipped. |
 * | `MbusErrFramingError` | **Timing violation detected** (see below). Receive buffer is cleared; server resumes listening. |
 * | `MbusErrIoError` / `MbusErrConnectionClosed` | Transport is marked disconnected. Call `mbus_serial_server_connect` to reopen. |
 * | `send` fails | Response is queued for retry on subsequent polls (up to `max_send_retries`). |
 * | CRC/parse error | One byte is discarded and the sliding window re-syncs. |
 *
 * - `MbusErrInvalidClientId` — returned only when `id` is not a valid serial slot.
 *
 * # Framing error handling
 *
 * When the C `recv` callback detects a t1.5 inter-character gap violation (a
 * silence of 1.5 character times *inside* a frame), it must return
 * `MBUS_ERR_FRAMING_ERROR`.  The server will:
 * - Discard all bytes buffered so far for the current frame.
 * - **Not** disconnect — the bus is still usable.
 * - Resume waiting for the next valid frame on the next poll call.
 *
 * This is the correct behaviour per Modbus Serial Line Specification §2.5.1.2.
 *
 * The server lock must be held while calling this function.
 */
enum MbusStatusCode mbus_serial_server_poll(MbusServerId id);

/**
 * Returns `true` if the serial server's transport is connected.
 *
 * Delegates to the `is_connected` function-pointer in `MbusTransportCallbacks`.
 * Returns `false` for an invalid or freed server ID.
 */
bool mbus_serial_server_is_connected(MbusServerId id);

/**
 * Returns the number of requests waiting in the priority queue.
 *
 * For serial servers the queue depth is fixed at 1 (half-duplex bus allows
 * only one request in flight), so this will always be 0 or 1.
 * Returns `0` for an invalid or freed server ID.
 */
uintptr_t mbus_serial_server_pending_request_count(MbusServerId id);

/**
 * Returns the number of responses waiting for retry (failed sends).
 *
 * A non-zero value means the `send` transport callback has failed at least once
 * and the server is holding the unsent frame for retry on the next poll.
 * Returns `0` for an invalid or freed server ID.
 */
uintptr_t mbus_serial_server_pending_response_count(MbusServerId id);

/**
 * Global pool lock — held only during create/destroy operations. Reuses
 * the same symbol exported by the client pool.
 */
extern void mbus_pool_lock(void);

/**
 * Release the global pool lock.
 */
extern void mbus_pool_unlock(void);

#endif  /* MODBUS_RS_SERVER_H */
